[package]
name = "tk_os"
version = "0.0.1"
authors = ["kalucky0 <kalucki23@gmail.com>"]
edition = "2021"

[workspace]
members = [
    "boot",
]

[dependencies]
bootloader = "0.10.9"
bit_field = "0.10.0"
volatile = "0.2.6"
spin = "0.5.2"
x86_64 = "0.14.6"
uart_16550 = "0.2.15"
pic8259 = "0.10.2"
pc-keyboard = "0.5.1"
linked_list_allocator = "0.9.1"
log = "0.4.14"
spinning_top = "0.2.4"
time = { version = "0.2.27", default-features = false }
font8x8 = { version = "0.2.5", default-features = false, features = ["unicode"] }

[package.metadata.bootloader]
map-physical-memory = true

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]

[dependencies.crossbeam-queue]
version = "0.2.1"
default-features = false
features = ["alloc"]

[dependencies.conquer-once]
version = "0.2.0"
default-features = false

[dependencies.futures-util]
version = "0.3.4"
default-features = false
features = ["alloc"]